CREATE OR REPLACE DATABASE P1_DB;
CREATE OR REPLACE SCHEMA BRONZE;

-- CREATING S3 INTEGRATION
CREATE OR REPLACE STORAGE INTEGRATION S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::000185048470:role/project-1-snowflake-role'
  -- STORAGE_ALLOWED_LOCATIONS = ('s3://project-1-raw-data-bucket/small-data/');
  STORAGE_ALLOWED_LOCATIONS = ('s3://project-1-raw-data-bucket/data/');

DESC INTEGRATION S3_INT;

-- CREATING CSV FILE FORMAT
CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null', 'NA')
  EMPTY_FIELD_AS_NULL = true;

-- CREATING EXTERNAL STAGE
CREATE OR REPLACE STAGE P1_DB.BRONZE.P1_STAGE 
  STORAGE_INTEGRATION = S3_INT
  -- URL = 's3://project-1-raw-data-bucket/small-data/'
  URL = 's3://project-1-raw-data-bucket/data/'
  FILE_FORMAT = MY_CSV_FORMAT;

LIST @P1_DB.BRONZE.P1_STAGE;

-- CREATING BRONZE LAYER RAW TABLE
CREATE OR REPLACE TABLE P1_DB.BRONZE.STORES (
    STORE NUMBER(38,0) NOT NULL,
    TYPE VARCHAR(255) COLLATE 'en-ci' NOT NULL,
    SIZE NUMBER(38,0) NOT NULL,
    INSERT_DTS TIMESTAMP_NTZ(6) NOT NULL,
    UPDATE_DTS TIMESTAMP_NTZ(6) NOT NULL,
    SOURCE_FILE_NAME VARCHAR(255) NOT NULL,
    SOURCE_FILE_ROW_NUMBER VARCHAR(255) NOT NULL);

CREATE OR REPLACE TABLE P1_DB.BRONZE.DEPARTMENT (
    STORE NUMBER(38,0) NOT NULL,
    DEPT NUMBER(38,0) NOT NULL,
    DATE DATE NOT NULL,
    WEEKLY_SALES NUMBER(38,2) NOT NULL,
    ISHOLIDAY BOOLEAN NOT NULL,
    INSERT_DTS TIMESTAMP_NTZ(6) NOT NULL,
    UPDATE_DTS TIMESTAMP_NTZ(6) NOT NULL,
    SOURCE_FILE_NAME VARCHAR(255) NOT NULL,
    SOURCE_FILE_ROW_NUMBER VARCHAR(255) NOT NULL);

CREATE OR REPLACE TABLE P1_DB.BRONZE.FACT (
    STORE NUMBER(38,0) NOT NULL,
    DATE DATE NOT NULL,
    TEMPERATURE NUMBER(10,2),
    FUEL_PRICE NUMBER(10,3),
    MARKDOWN1 NUMBER(38,2),
    MARKDOWN2 NUMBER(38,2),
    MARKDOWN3 NUMBER(38,2),
    MARKDOWN4 NUMBER(38,2),
    MARKDOWN5 NUMBER(38,2),
    CPI NUMBER(38,7),
    UNEMPLOYMENT NUMBER(38,3),
    ISHOLIDAY BOOLEAN,
    INSERT_DTS TIMESTAMP_NTZ(6) NOT NULL,
    UPDATE_DTS TIMESTAMP_NTZ(6) NOT NULL,
    SOURCE_FILE_NAME VARCHAR(255) NOT NULL,
    SOURCE_FILE_ROW_NUMBER VARCHAR(255) NOT NULL);

--------------------------------------------------------------
---------------- RUN DBT MODELS ------------------------------
--------------------------------------------------------------
---------------- PRESENTING TABLES ---------------------------

-- BRONZE LAYER TABLES
SELECT * FROM P1_DB.BRONZE.STORES;
SELECT * FROM P1_DB.BRONZE.DEPARTMENT;
SELECT * FROM P1_DB.BRONZE.FACT;

-- SILVER LAYER TABLES
SELECT * FROM P1_DB.SILVER.DATE_DIM;
SELECT * FROM P1_DB.SILVER.STORE_DIM;

-- SNAPSHOTS
SELECT * FROM P1_DB.SNAPSHOTS.STORE_SNAPSHOTS;

-- GOLD LAYER TABLE
SELECT * FROM P1_DB.GOLD.FACT_TABLE;



-- CLEAN EVERYTHING
-- TRUNCATE TABLE P1_DB.BRONZE.STORES;
-- TRUNCATE TABLE P1_DB.BRONZE.DEPARTMENT;
-- TRUNCATE TABLE P1_DB.BRONZE.FACT;
-- DROP TABLE P1_DB.SILVER.DATE_DIM;
-- DROP TABLE P1_DB.SILVER.STORE_DIM;
-- DROP TABLE P1_DB.SNAPSHOTS.STORE_SNAPSHOTS;
-- DROP TABLE P1_DB.GOLD.FACT_TABLE;
